"""Synthetic, non-promoting corpus for benchmarking and testing the orchestrator.

This is scaffolding, and it is built so that it cannot be mistaken for evidence.

Every row it produces carries :data:`FIXTURE_PROVENANCE`, which contains the word
``synthetic`` and therefore matches
:data:`calibration_evidence.SYNTHETIC_PROVENANCE_PATTERNS`. Any attempt to mount
this as a governed source is refused by the module that already exists to refuse
it, rather than by a reviewer noticing. :func:`assert_refused_as_governed_source`
proves that interlock holds instead of asserting it.

It exists for two jobs and no others:

* measuring how long a candidate evaluation takes, so a shard count can be chosen
  before real inputs arrive;
* exercising the scorer's temporal and identification guards against a corpus
  whose true parameters are known, which is the only way to test that a leakage
  refusal fires on a leak rather than on nothing.

It answers no modelling question. Its point axis is the identity axis, which is
precisely the assumption the governed expected-margin lane exists to replace, and
its "true" team strengths are arithmetic rather than football. A result measured
here is a timing, never a finding.

The generator takes an explicit seed and uses a fixed linear congruential
sequence rather than :mod:`random`, so a fixture is reproducible across processes
and Python versions without depending on the global RNG's implementation.
"""

from __future__ import annotations

import hashlib
from typing import Any, Sequence

from .calibration_scoring import (
    ExpectedMarginAuthority,
    ObservationRow,
    ObservationSet,
    fixture_authority,
)
from .calibration_search import canonical_json
from .errors import GovernanceBlock

__all__ = [
    "FIXTURE_DATASET_SHA_PREFIX",
    "FIXTURE_PROVENANCE",
    "assert_refused_as_governed_source",
    "fixture_authority",
    "fixture_observations",
]

#: Deliberately contains "synthetic" so the governed mount path refuses it.
FIXTURE_PROVENANCE = (
    "SYNTHETIC_FIXTURE_NON_PROMOTING: generated by calibration_fixture for "
    "benchmarking and tests. Not observed. Never admissible as calibration evidence."
)

#: Prefixed so the digest can never be mistaken for one taken over governed bytes.
FIXTURE_DATASET_SHA_PREFIX = "FIXTURE-"

#: Constants of a standard 48-bit LCG. Named so the sequence is reproducible by
#: anyone reading this rather than only by re-running it.
_LCG_MULTIPLIER = 25214903917
_LCG_INCREMENT = 11
_LCG_MODULUS = 1 << 48


class _Lcg:
    """Deterministic uniform stream. Values in [-1, 1)."""

    def __init__(self, seed: int) -> None:
        self._state = int(seed) % _LCG_MODULUS

    def next_unit(self) -> float:
        self._state = (_LCG_MULTIPLIER * self._state + _LCG_INCREMENT) % _LCG_MODULUS
        return (self._state / _LCG_MODULUS) * 2.0 - 1.0


def _round_robin(team_count: int, round_index: int) -> list[tuple[int, int]]:
    """Circle-method pairings. Every team plays exactly once per round."""
    if team_count % 2 or team_count < 4:
        raise ValueError("Fixture requires an even team count of at least 4.")
    others = list(range(1, team_count))
    span = len(others)
    offset = round_index % span
    rotated = others[offset:] + others[:offset]
    pairs = [(0, rotated[0])]
    for i in range(1, team_count // 2):
        pairs.append((rotated[i], rotated[span - i]))
    return pairs


def fixture_observations(
    *,
    seasons: Sequence[int] = (2021, 2022, 2023),
    team_count: int = 24,
    weeks: int = 12,
    seed: int = 20260822,
    noise_points: float = 12.0,
    hfa_points: float = 2.5,
) -> ObservationSet:
    """Build a chronologically ordered synthetic corpus with a temporal partition.

    The split is by season and is strictly ordered in time — earliest seasons
    train, the penultimate season validates, the final season is holdout — because
    :meth:`ObservationSet.require_temporal_split_integrity` refuses anything else,
    and a fixture that could not pass the real gate would test nothing.
    """
    if len(seasons) < 3:
        raise ValueError(
            "A fixture needs at least three seasons: the temporal partition requires "
            "one each for training, validation and holdout."
        )
    rng = _Lcg(seed)
    # True strengths are arithmetic, not football. Spread symmetrically about zero
    # so the identity point axis produces margins of a plausible magnitude.
    true_strength = [
        ((i * 37) % team_count) - (team_count - 1) / 2.0 for i in range(team_count)
    ]
    authority = fixture_authority(hfa_points=hfa_points)

    validation_season = seasons[-2]
    holdout_season = seasons[-1]

    rows: list[ObservationRow] = []
    for season_index, season in enumerate(seasons):
        # Opening ratings are the truth plus a season-specific error, so the model
        # has something to learn rather than starting already correct.
        opening = [
            true_strength[i] + noise_points * 0.25 * rng.next_unit()
            for i in range(team_count)
        ]
        if season == holdout_season:
            split = "holdout"
        elif season == validation_season:
            split = "validation"
        else:
            split = "training"

        for week in range(1, weeks + 1):
            for slot, (home, away) in enumerate(_round_robin(team_count, week - 1)):
                venue = "NEUTRAL" if (week + slot) % 11 == 0 else "HOME"
                signed_hfa = authority.signed_hfa(venue)
                margin = (
                    true_strength[home]
                    - true_strength[away]
                    + signed_hfa
                    + noise_points * rng.next_unit()
                )
                if margin == 0.0:
                    margin = 0.5
                # Kickoff instants are hourly within a week so that ordering inside a
                # week is total and the leakage proof has something to check.
                event_time = (
                    f"{season:04d}-{(week // 4) + 8:02d}-"
                    f"{(week % 28) + 1:02d}T{(slot % 12) + 9:02d}:00:00+00:00"
                )
                rows.append(
                    ObservationRow(
                        game_id=f"G{season}-W{week:02d}-S{slot:02d}",
                        season=season,
                        week=week,
                        event_time=event_time,
                        team=f"T{home:03d}",
                        opponent=f"T{away:03d}",
                        venue=venue,
                        pregame_team_points=opening[home],
                        pregame_opponent_points=opening[away],
                        governed_expected_margin=(
                            opening[home] - opening[away] + signed_hfa
                        ),
                        actual_margin=margin,
                        split=split,
                        provenance=FIXTURE_PROVENANCE,
                    )
                )
        del season_index

    digest = hashlib.sha256(
        canonical_json([r.as_dict() for r in rows]).encode("utf-8")
    ).hexdigest()
    return ObservationSet(
        rows=tuple(rows),
        dataset_sha=f"{FIXTURE_DATASET_SHA_PREFIX}{digest}",
        provenance=FIXTURE_PROVENANCE,
    )


def assert_refused_as_governed_source() -> dict[str, Any]:
    """Prove the governed mount path refuses this fixture's provenance.

    The claim "this fixture can never be promoted" is only worth something if the
    refusal is executed rather than described. This runs the real check from
    :mod:`.calibration_evidence` against :data:`FIXTURE_PROVENANCE` and raises if
    it would have been admitted.
    """
    from .calibration_evidence import SYNTHETIC_PROVENANCE_PATTERNS

    folded = FIXTURE_PROVENANCE.casefold()
    matched = sorted(p for p in SYNTHETIC_PROVENANCE_PATTERNS if p in folded)
    if not matched:
        raise GovernanceBlock(
            "Fixture provenance no longer matches any synthetic-source pattern, so the "
            "governed mount path would admit it. The fixture must remain unmountable."
        )
    return {
        "provenance": FIXTURE_PROVENANCE,
        "matched_synthetic_patterns": matched,
        "admissible_as_governed_source": False,
    }
