"""Synthetic, non-promoting corpus for benchmarking and testing the orchestrator.

This is scaffolding, and it is built so that it cannot be mistaken for evidence.

Every row it produces carries :data:`FIXTURE_PROVENANCE`, which contains the word
``synthetic`` and therefore matches
:data:`calibration_evidence.SYNTHETIC_PROVENANCE_PATTERNS`. Any attempt to mount
this as a governed source is refused by the module that already exists to refuse
it, rather than by a reviewer noticing. :func:`assert_refused_as_governed_source`
proves that interlock holds instead of asserting it.

It exists for two jobs and no others:

* measuring how long a candidate evaluation takes, so a shard count can be chosen
  before real inputs arrive;
* exercising the scorer's temporal and identification guards against a corpus
  whose true parameters are known, which is the only way to test that a leakage
  refusal fires on a leak rather than on nothing.

It answers no modelling question. Its point axis is the identity axis, which is
precisely the assumption the governed expected-margin lane exists to replace, and
its "true" team strengths are arithmetic rather than football. A result measured
here is a timing, never a finding.

The generator takes an explicit seed and uses a fixed linear congruential
sequence rather than :mod:`random`, so a fixture is reproducible across processes
and Python versions without depending on the global RNG's implementation.
"""

from __future__ import annotations

import hashlib
from dataclasses import replace
from typing import Any, Sequence

from .calibration_scoring import (
    ExpectedMarginAuthority,
    ObservationRow,
    ObservationSet,
    STRUCTURE_GOVERNED,
    fixture_authority,
)
from .calibration_search import canonical_json
from .calibration_stage0 import (
    PRODUCER_OPENING_STATE,
    PRODUCER_VENUE_CLASSIFICATION,
    SealedInput,
    opening_state_key,
)
from .errors import GovernanceBlock

__all__ = [
    "FIXTURE_DATASET_SHA_PREFIX",
    "FIXTURE_PROVENANCE",
    "TRUE_POINT_SCALE",
    "assert_refused_as_governed_source",
    "fixture_authority",
    "fixture_observations",
    "fixture_opening_standardized_state",
    "fixture_venue_classification",
    "governed_structure_for_tests",
]

#: The scale the fixture's margins are generated at, in points per standardized
#: unit. Stage 0 should recover a neighbourhood of this from Weeks 1-2, which is
#: what makes "the scale is identifiable" a test rather than an assertion.
TRUE_POINT_SCALE = 12.0

#: Deliberately contains "synthetic" so the governed mount path refuses it.
FIXTURE_PROVENANCE = (
    "SYNTHETIC_FIXTURE_NON_PROMOTING: generated by calibration_fixture for "
    "benchmarking and tests. Not observed. Never admissible as calibration evidence."
)

#: Prefixed so the digest can never be mistaken for one taken over governed bytes.
FIXTURE_DATASET_SHA_PREFIX = "FIXTURE-"

#: Constants of a standard 48-bit LCG. Named so the sequence is reproducible by
#: anyone reading this rather than only by re-running it.
_LCG_MULTIPLIER = 25214903917
_LCG_INCREMENT = 11
_LCG_MODULUS = 1 << 48


class _Lcg:
    """Deterministic uniform stream. Values in [-1, 1)."""

    def __init__(self, seed: int) -> None:
        self._state = int(seed) % _LCG_MODULUS

    def next_unit(self) -> float:
        self._state = (_LCG_MULTIPLIER * self._state + _LCG_INCREMENT) % _LCG_MODULUS
        return (self._state / _LCG_MODULUS) * 2.0 - 1.0


def _round_robin(team_count: int, round_index: int) -> list[tuple[int, int]]:
    """Circle-method pairings. Every team plays exactly once per round."""
    if team_count % 2 or team_count < 4:
        raise ValueError("Fixture requires an even team count of at least 4.")
    others = list(range(1, team_count))
    span = len(others)
    offset = round_index % span
    rotated = others[offset:] + others[:offset]
    pairs = [(0, rotated[0])]
    for i in range(1, team_count // 2):
        pairs.append((rotated[i], rotated[span - i]))
    return pairs


def _true_strengths(team_count: int) -> list[float]:
    """Arithmetic, not football. Spread symmetrically about zero."""
    return [((i * 37) % team_count) - (team_count - 1) / 2.0 for i in range(team_count)]


def fixture_opening_standardized_state(
    *, seasons: Sequence[int] = (2021, 2022, 2023), team_count: int = 24
) -> SealedInput:
    """Stand-in for Agent 6's output: opening strength in standardized units.

    Generated as ``true_strength / TRUE_POINT_SCALE`` so that a candidate scale of
    :data:`TRUE_POINT_SCALE` reproduces the fixture's margins exactly, up to noise.
    Sealed the same way a real upstream payload would be, so the digest check is
    exercised rather than bypassed.
    """
    truth = _true_strengths(team_count)
    payload = {
        opening_state_key(season, f"T{i:03d}"): truth[i] / TRUE_POINT_SCALE
        for season in seasons
        for i in range(team_count)
    }
    return SealedInput.seal(
        input_id="FIXTURE_OPENING_STANDARDIZED_STATE",
        producer=PRODUCER_OPENING_STATE,
        payload=payload,
    )


def fixture_venue_classification(
    *, seasons: Sequence[int] = (2021, 2022, 2023), hfa_points: float = 2.5
) -> SealedInput:
    """Stand-in for Agent 5's output: the venue/HFA classification for used games."""
    return SealedInput.seal(
        input_id="FIXTURE_VENUE_CLASSIFICATION",
        producer=PRODUCER_VENUE_CLASSIFICATION,
        payload={
            f"{season}": {
                "hfa_points": float(hfa_points),
                "neutral_site_adjustment_points": 0.0,
                "classification": "FIXTURE_DETERMINISTIC",
            }
            for season in seasons
        },
    )


def governed_structure_for_tests(
    *, hfa_points: float = 2.5, points_per_standardized_unit: float | None = None
) -> ExpectedMarginAuthority:
    """A governed *structure* for exercising Stage 0 and the research gate.

    This is arithmetic, not evidence, which is why it may legitimately be built in
    a test while a synthetic *corpus* may not: the structure states subject
    orientation, point domain and venue semantics, and a test asserting how the
    scorer behaves under them has to be able to state them.

    Constructing this is not the audited model layer having produced one. The gate
    that actually blocks a real run is the corpus gate, which no fixture clears.
    """
    base = fixture_authority(
        hfa_points=hfa_points, points_per_standardized_unit=points_per_standardized_unit
    )
    return replace(
        base,
        authority_id="TEST_GOVERNED_EXPECTED_MARGIN_STRUCTURE",
        structure_status=STRUCTURE_GOVERNED,
    )


def fixture_observations(
    *,
    seasons: Sequence[int] = (2021, 2022, 2023),
    team_count: int = 24,
    weeks: int = 12,
    seed: int = 20260822,
    noise_points: float = 12.0,
    hfa_points: float = 2.5,
    fcs_games_per_season: int = 2,
) -> ObservationSet:
    """Build a chronologically ordered synthetic corpus with a temporal partition.

    The split is by season and is strictly ordered in time — earliest seasons
    train, the penultimate season validates, the final season is holdout — because
    :meth:`ObservationSet.require_temporal_split_integrity` refuses anything else,
    and a fixture that could not pass the real gate would test nothing.
    """
    if len(seasons) < 3:
        raise ValueError(
            "A fixture needs at least three seasons: the temporal partition requires "
            "one each for training, validation and holdout."
        )
    rng = _Lcg(seed)
    true_strength = _true_strengths(team_count)
    authority = fixture_authority(hfa_points=hfa_points)

    validation_season = seasons[-2]
    holdout_season = seasons[-1]

    rows: list[ObservationRow] = []
    for season_index, season in enumerate(seasons):
        # Opening ratings are the truth plus a season-specific error, so the model
        # has something to learn rather than starting already correct.
        opening = [
            true_strength[i] + noise_points * 0.25 * rng.next_unit()
            for i in range(team_count)
        ]
        if season == holdout_season:
            split = "holdout"
        elif season == validation_season:
            split = "validation"
        else:
            split = "training"

        for week in range(1, weeks + 1):
            for slot, (home, away) in enumerate(_round_robin(team_count, week - 1)):
                venue = "NEUTRAL" if (week + slot) % 11 == 0 else "HOME"
                signed_hfa = authority.signed_venue_adjustment(venue)
                margin = (
                    true_strength[home]
                    - true_strength[away]
                    + signed_hfa
                    + noise_points * rng.next_unit()
                )
                if margin == 0.0:
                    margin = 0.5
                # Kickoff instants are hourly within a week so that ordering inside a
                # week is total and the leakage proof has something to check.
                event_time = (
                    f"{season:04d}-{(week // 4) + 8:02d}-"
                    f"{(week % 28) + 1:02d}T{(slot % 12) + 9:02d}:00:00+00:00"
                )
                rows.append(
                    ObservationRow(
                        game_id=f"G{season}-W{week:02d}-S{slot:02d}",
                        season=season,
                        week=week,
                        event_time=event_time,
                        team=f"T{home:03d}",
                        opponent=f"T{away:03d}",
                        venue=venue,
                        pregame_team_points=opening[home],
                        pregame_opponent_points=opening[away],
                        governed_expected_margin=(
                            opening[home] - opening[away] + signed_hfa
                        ),
                        actual_margin=margin,
                        split=split,
                        provenance=FIXTURE_PROVENANCE,
                    )
                )
        # A handful of FCS games per season, so "excluded" is something the tests
        # can observe rather than something the code merely claims. Their opponents
        # deliberately carry no opening standardized state, so a regression that
        # stopped excluding them would fail loudly in Stage 0 rather than quietly
        # fitting them on the very axis Stage 0 is identifying.
        for extra in range(fcs_games_per_season):
            home = (extra * 5) % team_count
            venue = "HOME"
            signed_hfa = authority.signed_venue_adjustment(venue)
            rows.append(
                ObservationRow(
                    game_id=f"G{season}-FCS{extra:02d}",
                    season=season,
                    week=1,
                    event_time=f"{season:04d}-08-01T12:{extra:02d}:00+00:00",
                    team=f"T{home:03d}",
                    opponent=f"F{extra:03d}",
                    venue=venue,
                    pregame_team_points=opening[home],
                    pregame_opponent_points=opening[home] - 21.0,
                    governed_expected_margin=21.0 + signed_hfa,
                    actual_margin=21.0 + noise_points * 0.25 * rng.next_unit(),
                    split=split,
                    provenance=FIXTURE_PROVENANCE,
                    opponent_division="FCS",
                )
            )
        del season_index

    digest = hashlib.sha256(
        canonical_json([r.as_dict() for r in rows]).encode("utf-8")
    ).hexdigest()
    return ObservationSet(
        rows=tuple(rows),
        dataset_sha=f"{FIXTURE_DATASET_SHA_PREFIX}{digest}",
        provenance=FIXTURE_PROVENANCE,
    )


def assert_refused_as_governed_source() -> dict[str, Any]:
    """Prove the governed mount path refuses this fixture's provenance.

    The claim "this fixture can never be promoted" is only worth something if the
    refusal is executed rather than described. This runs the real check from
    :mod:`.calibration_evidence` against :data:`FIXTURE_PROVENANCE` and raises if
    it would have been admitted.
    """
    from .calibration_evidence import SYNTHETIC_PROVENANCE_PATTERNS

    folded = FIXTURE_PROVENANCE.casefold()
    matched = sorted(p for p in SYNTHETIC_PROVENANCE_PATTERNS if p in folded)
    if not matched:
        raise GovernanceBlock(
            "Fixture provenance no longer matches any synthetic-source pattern, so the "
            "governed mount path would admit it. The fixture must remain unmountable."
        )
    return {
        "provenance": FIXTURE_PROVENANCE,
        "matched_synthetic_patterns": matched,
        "admissible_as_governed_source": False,
    }
