"""The epistemic disposition of a production parameter, and what it permits.

R1 could represent one thing: a parameter was fitted, or the run refused. The R2
evidence proves the final V3 vector will not look like that. Some parameters
carry a fitted number, some carry a governed number nobody fitted, some carry a
number a human has to choose, and some carry no number at all because the
evidence cannot produce one. Those are different epistemic claims, and a
recommendation that flattened them into "value / no value" would tell an
approver less than the run actually knows.

So a disposition is a first-class value here, and every governed parameter
carries exactly one. Nine are recognised and the set is closed: an unrecognised
disposition is refused rather than treated as unknown-but-probably-fine, for the
same reason ``UNCLASSIFIED`` circularity is refused in :mod:`.evidence`.

Three properties do the work
-----------------------------

**Only one disposition may enter an estimator.** :data:`ESTIMATOR_ADMISSIBLE` is
``(FIT_RESULT,)`` and :func:`require_estimator_admissible` is what every
numerical stage calls. A circular parameter cannot reach a search by being
described differently, because the search asks about the disposition rather than
about the words in the rationale.

**Carrying a value and having been measured are different facts.**
:data:`CARRIES_VALUE` names the four dispositions under which a number is
legitimate -- a fit result, a fixed prior, a prior-only value, and a residual
derived from other accepted quantities. The rest must recommend ``None``, and
:func:`require_value_consistent` refuses the combination rather than trusting a
note beside it.

**Absence is classified, not silently tolerated.** A parameter with no value is
either a thing a human must choose or a fail-closed hole.
:data:`PRODUCTION_VALUE_SEMANTICS` says which, per parameter, and
:func:`execution_obstacles` turns that into the concrete list of reasons a run
may not enter its execution tiers. This is where the FCS doctrine lives: the FCS
point adapter is required *at its use site*, so a run whose adapter is
:data:`MISSING_FAIL_CLOSED` may execute, and every FCS game that needs a point
adapter fails closed instead of receiving an invented number.
"""

from __future__ import annotations

from typing import Any, Mapping

from ..errors import GovernanceBlock, InputValidationError
from .evidence import (
    BLOCKED,
    CIRCULAR_NOT_IDENTIFIABLE as ELIGIBILITY_CIRCULAR,
    FIT_ALLOWED,
    FIXED,
    GOVERNED_PARAMETERS,
    MISSING,
    PRIOR_ONLY as ELIGIBILITY_PRIOR_ONLY,
    WITNESS_ONLY as ELIGIBILITY_WITNESS_ONLY,
)

__all__ = [
    "CARRIES_VALUE",
    "CIRCULAR_NOT_IDENTIFIABLE",
    "DISPOSITIONS",
    "ESTIMATOR_ADMISSIBLE",
    "FIT_RESULT",
    "FIXED_PRIOR",
    "HUMAN_SELECTED",
    "HUMAN_SELECTION_REQUIRED",
    "MISSING_FAIL_CLOSED",
    "NON_FIT_DISPOSITIONS",
    "PRIOR_ONLY",
    "PRODUCTION_VALUE_SEMANTICS",
    "RECENT_FORM_UNIDENTIFIED_REASON",
    "REQUIRES_HUMAN_DISPOSITION",
    "RESIDUAL_DERIVED",
    "UNIDENTIFIED",
    "VALUE_REQUIRED_AT_USE_SITE",
    "VALUE_REQUIRED_FOR_EXECUTION",
    "WITNESS_ONLY",
    "disposition_for_eligibility",
    "execution_obstacles",
    "require_estimator_admissible",
    "require_known_disposition",
    "require_value_consistent",
    "use_site_fail_closed",
]


# --- the nine dispositions ---------------------------------------------------

#: A deterministic search ran and identified a value. The only disposition that
#: is a measurement made by this run.
FIT_RESULT = "FIT_RESULT"

#: A governed value already existed and is carried forward unchanged. Nothing
#: measured it here and nothing claims to have.
FIXED_PRIOR = "FIXED_PRIOR"

#: The evidence supports a prior rather than an estimate. A number travels, and
#: it is explicitly not a fit.
PRIOR_ONLY = "PRIOR_ONLY"

#: The objective could not distinguish a value. No number, and the absence is
#: the finding.
UNIDENTIFIED = "UNIDENTIFIED"

#: The evidence was generated by the mechanism under estimation. Fitting it
#: would recover the generator's own setting; not identifiable in principle from
#: this evidence, rather than merely unresolved in practice.
CIRCULAR_NOT_IDENTIFIABLE = "CIRCULAR_NOT_IDENTIFIABLE"

#: No admissible evidence selects a value and production needs one. The choice
#: is a human act, and it is requested at the single approval gate.
HUMAN_SELECTION_REQUIRED = "HUMAN_SELECTION_REQUIRED"

#: The value is determined by other accepted quantities rather than fitted
#: independently. Recorded as derived so nobody later cites it as evidence for
#: the quantities it was derived from.
RESIDUAL_DERIVED = "RESIDUAL_DERIVED"

#: The manifest holds no evidence for the parameter at all. Accepted as a state
#: of knowledge; refused as a basis for execution wherever production needs the
#: value.
MISSING_FAIL_CLOSED = "MISSING_FAIL_CLOSED"

#: The field diagnoses plausibility and may never select a value.
WITNESS_ONLY = "WITNESS_ONLY"

DISPOSITIONS: tuple[str, ...] = (
    FIT_RESULT,
    FIXED_PRIOR,
    PRIOR_ONLY,
    UNIDENTIFIED,
    CIRCULAR_NOT_IDENTIFIABLE,
    HUMAN_SELECTION_REQUIRED,
    RESIDUAL_DERIVED,
    MISSING_FAIL_CLOSED,
    WITNESS_ONLY,
)

#: The single disposition a numerical search may produce, and therefore the
#: single one an estimator may be entered for.
ESTIMATOR_ADMISSIBLE: tuple[str, ...] = (FIT_RESULT,)

#: Everything else. Named so a caller can assert "this is a non-fit disposition"
#: without enumerating eight strings and missing the ninth when it is added.
NON_FIT_DISPOSITIONS: tuple[str, ...] = tuple(
    d for d in DISPOSITIONS if d not in ESTIMATOR_ADMISSIBLE
)

#: Dispositions under which a recommended value is legitimate. Every other
#: disposition must recommend ``None``.
CARRIES_VALUE: tuple[str, ...] = (
    FIT_RESULT,
    FIXED_PRIOR,
    PRIOR_ONLY,
    RESIDUAL_DERIVED,
)

#: The one disposition whose value is optional rather than determined.
#:
#: :data:`HUMAN_SELECTION_REQUIRED` describes a parameter whose value is a human
#: act. Before the gate it carries no value -- that is the question. After the
#: gate it carries whatever the approver chose, recorded as a selection rather
#: than as a measurement, which is the distinction the disposition exists to
#: preserve. So it is the single disposition for which both states are legal,
#: and the constraint that separates "has a number" from "was measured" is
#: enforced everywhere else.
HUMAN_SELECTED: tuple[str, ...] = (HUMAN_SELECTION_REQUIRED,)

#: Dispositions that put a question in front of the human at the one gate.
REQUIRES_HUMAN_DISPOSITION: tuple[str, ...] = (
    HUMAN_SELECTION_REQUIRED,
    MISSING_FAIL_CLOSED,
    UNIDENTIFIED,
    CIRCULAR_NOT_IDENTIFIABLE,
)

#: The reason code the R2 evidence attaches to ``recent_form_weights``. A named
#: constant rather than free text, so the recommendation, the approval and the
#: final report all cite the same string.
RECENT_FORM_UNIDENTIFIED_REASON = "RECENT_FORM_UNIDENTIFIED_FROM_SYNTHETIC_EVIDENCE"


# --- what production actually needs ------------------------------------------

#: Production cannot run a path without the value. An absent one blocks the
#: execution tiers outright.
VALUE_REQUIRED_FOR_EXECUTION = "VALUE_REQUIRED_FOR_EXECUTION"

#: Production runs, and the specific code path that needs the value refuses.
#: The run is not blocked; the use site is.
VALUE_REQUIRED_AT_USE_SITE = "VALUE_REQUIRED_AT_USE_SITE"

#: Every governed parameter, and which of the two it is.
#:
#: Everything the weekly rerating and game-outcome mathematics reads is
#: :data:`VALUE_REQUIRED_FOR_EXECUTION`, including ``weekly_movement_cap_points``:
#: the rerating policy takes a cap as a float, so "the cap never binds among the
#: finalists" is a finding about the objective, not a configuration production
#: can run without. The one exception is the FCS point adapter, read only where
#: an FBS-vs-FCS game needs a point representation -- so its absence is a
#: fail-closed use site rather than an unrunnable season.
PRODUCTION_VALUE_SEMANTICS: dict[str, str] = {
    "weekly_performance_residual_coefficient": VALUE_REQUIRED_FOR_EXECUTION,
    "weekly_movement_cap_points": VALUE_REQUIRED_FOR_EXECUTION,
    "recent_form_weights": VALUE_REQUIRED_FOR_EXECUTION,
    "blowout_treatment": VALUE_REQUIRED_FOR_EXECUTION,
    "sample_size_regularization": VALUE_REQUIRED_FOR_EXECUTION,
    "game_sd_points": VALUE_REQUIRED_FOR_EXECUTION,
    "point_scale": VALUE_REQUIRED_FOR_EXECUTION,
    "fcs_point_adapter": VALUE_REQUIRED_AT_USE_SITE,
}

#: How a manifest eligibility maps onto a disposition before any stage has run.
#: A fittable parameter has no disposition yet -- it has permission -- so it is
#: absent here and resolved from its search outcome instead.
_ELIGIBILITY_DISPOSITION: dict[str, str] = {
    FIXED: FIXED_PRIOR,
    ELIGIBILITY_PRIOR_ONLY: PRIOR_ONLY,
    ELIGIBILITY_CIRCULAR: CIRCULAR_NOT_IDENTIFIABLE,
    ELIGIBILITY_WITNESS_ONLY: WITNESS_ONLY,
    MISSING: MISSING_FAIL_CLOSED,
    BLOCKED: HUMAN_SELECTION_REQUIRED,
}


def require_known_disposition(parameter: str, disposition: str) -> str:
    """Assert ``disposition`` is one of the nine, or refuse."""
    if disposition not in DISPOSITIONS:
        raise InputValidationError(
            f"Parameter {parameter} carries unknown disposition {disposition!r}; "
            f"expected one of {list(DISPOSITIONS)}."
        )
    return disposition


def disposition_for_eligibility(eligibility: str) -> str | None:
    """The disposition a manifest eligibility implies, or ``None`` if it fits.

    ``FIT_ALLOWED`` deliberately returns ``None``. Permission to search is not a
    result, and mapping it to :data:`FIT_RESULT` here would let a parameter
    arrive at the recommendation described as fitted without a search having run.
    """
    if eligibility == FIT_ALLOWED:
        return None
    try:
        return _ELIGIBILITY_DISPOSITION[eligibility]
    except KeyError:
        raise InputValidationError(
            f"No disposition is defined for eligibility {eligibility!r}."
        ) from None


def require_estimator_admissible(parameter: str, disposition: str) -> None:
    """Refuse to enter an estimator for a non-fit disposition.

    The message names the disposition, because "may not be fitted" and "may not
    be fitted *because the evidence is its own output*" are different facts, and
    the second one is what an operator needs.
    """
    require_known_disposition(parameter, disposition)
    if disposition not in ESTIMATOR_ADMISSIBLE:
        raise GovernanceBlock(
            f"{parameter} is {disposition} and must not enter an estimator. Only "
            f"{list(ESTIMATOR_ADMISSIBLE)} authorises a numerical search; every other "
            "disposition states that this run is not entitled to measure the parameter."
        )


def require_value_consistent(parameter: str, disposition: str, value: Any) -> None:
    """Refuse a value under a disposition that cannot carry one, and vice versa.

    :data:`HUMAN_SELECTION_REQUIRED` is exempt from both halves, and only it: it
    is legitimately valueless as a question and legitimately valued as an answer,
    and collapsing those two moments would either forbid the approver from
    answering or force the recommendation to answer on their behalf.
    """
    require_known_disposition(parameter, disposition)
    if disposition in HUMAN_SELECTED:
        return
    if disposition not in CARRIES_VALUE and value is not None:
        raise GovernanceBlock(
            f"{parameter} is {disposition} yet carries the value {value!r}. A "
            "disposition that records the absence of a measurement must not also "
            "report one; the finding is the absence."
        )
    if disposition in CARRIES_VALUE and value is None:
        raise GovernanceBlock(
            f"{parameter} is {disposition}, which carries a value, but none is "
            "recorded. A disposition that claims a number must have one."
        )


def execution_obstacles(
    vector: Mapping[str, Any], dispositions: Mapping[str, str]
) -> list[str]:
    """Why this vector may not enter the execution tiers, if it may not.

    One message per governed parameter that production needs a value for and
    does not have. An empty list is the only thing that authorises DEV, and it
    is computed from the approved vector rather than from a flag some earlier
    stage could have set.

    Parameters whose semantics are :data:`VALUE_REQUIRED_AT_USE_SITE` are
    deliberately absent from the result even when their value is missing: they
    do not block the run, they fail closed where they are read.
    """
    obstacles: list[str] = []
    for name in GOVERNED_PARAMETERS:
        if PRODUCTION_VALUE_SEMANTICS[name] != VALUE_REQUIRED_FOR_EXECUTION:
            continue
        if vector.get(name) is not None:
            continue
        disposition = dispositions.get(name, MISSING_FAIL_CLOSED)
        obstacles.append(
            f"{name} is {disposition} with no approved value, and production reads it "
            f"on every path ({VALUE_REQUIRED_FOR_EXECUTION}). Execution fails closed "
            "rather than substituting a default."
        )
    return obstacles


def use_site_fail_closed(
    vector: Mapping[str, Any], dispositions: Mapping[str, str]
) -> list[str]:
    """Which use sites will refuse because their value is absent.

    Not obstacles -- the run proceeds. Recorded so the freeze artifact says which
    parts of the model were unavailable, rather than leaving a reader to infer it
    from a missing column.
    """
    notices: list[str] = []
    for name in GOVERNED_PARAMETERS:
        if PRODUCTION_VALUE_SEMANTICS[name] != VALUE_REQUIRED_AT_USE_SITE:
            continue
        if vector.get(name) is not None:
            continue
        disposition = dispositions.get(name, MISSING_FAIL_CLOSED)
        notices.append(
            f"{name} is {disposition} with no approved value. Every use site that "
            "requires it fails closed; no value is invented for it."
        )
    return notices
