"""Board I-K artifact custody — content identity, schema, governed identities.

The rule this suite exists to enforce is that **content decides custody and a
filename never does**. Both directions are tested explicitly:

* the approved bytes verify under any name, including the browser
  de-duplication variants ``(3)``, ``(3)(1)`` and `` (1)`` that operators
  actually receive; and
* bytes that are not the approved artifact are refused under *every* name,
  including the exact canonical filename.

Everything that could plausibly be offered in place of the Board of Record —
Board I-H, the superseded predecessor, an unapproved candidate, a pytest
fixture, a synthetic workbook, a truncated or corrupted file, a re-saved copy —
is refused, and refused with a positive identification where one is possible.

The schema and identity layers are exercised directly, because an artifact that
fails the digest gate never reaches them: a fabricated workbook cannot be used
to test row validation, so synthetic grids are fed to the validators instead.
"""

from __future__ import annotations

import hashlib
import shutil
import zipfile
from pathlib import Path

import pytest
from openpyxl import Workbook, load_workbook

from ncaaf_engine.simulation.dynamic_weekly_mc_v3 import board_of_record as bor
from ncaaf_engine.simulation.dynamic_weekly_mc_v3.config import V3Config
from ncaaf_engine.simulation.dynamic_weekly_mc_v3.errors import (
    GovernanceBlock,
    InputValidationError,
)
from ncaaf_engine.simulation.dynamic_weekly_mc_v3.inputs import load_canonical_team_index

ROOT = Path(__file__).resolve().parents[2]
CONFIG = ROOT / "config/dynamic_weekly_mc_v3/v3_experimental.json"
INPUTS = ROOT / "reference/dynamic_weekly_mc_v3/inputs"
APPROVED = INPUTS / bor.BOARD_OF_RECORD_FILENAME


@pytest.fixture(scope="module")
def canonical_index():
    return load_canonical_team_index(
        INPUTS / "2026_TEAM_CANONICAL_MASTER_v2_LLM_GROUNDING.md"
    )


@pytest.fixture(scope="module")
def board():
    return bor.require_board_of_record(APPROVED)


def _synthetic_board(path: Path, rows: list[list[object]], sheet: str | None = None) -> Path:
    """A workbook shaped like the Board but built here — never the real artifact."""
    wb = Workbook()
    ws = wb.active
    ws.title = sheet or bor.BOARD_SHEET
    ws.append(["2026 BOARD I-K — SYNTHETIC TEST FIXTURE"])
    ws.append(["Generated by the test suite. Not a governed artifact."])
    ws.append(list(bor.BOARD_COLUMNS))
    for row in rows:
        ws.append(row)
    wb.save(path)
    return path


def _plausible_rows(count: int = 121) -> list[list[object]]:
    return [
        [i, f"Team {i}", f"T{i}", "Test", 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
         None, 0.5, "BLOCKED_INPUTS_UNAVAILABLE", i, 0, str(i)]
        for i in range(1, count + 1)
    ]


def _grid(rows: list[list[object]]) -> list[list[object]]:
    """Header row plus data rows, the shape ``_read_board_grid`` returns."""
    return [list(bor.BOARD_COLUMNS)] + [list(r) for r in rows]


# =============================================================================
# A — the approved artifact is mounted and verifies on both digests
# =============================================================================


def test_the_mounted_artifact_is_the_approved_binary():
    assert APPROVED.exists()
    assert hashlib.sha256(APPROVED.read_bytes()).hexdigest() == (
        bor.BOARD_OF_RECORD_APPROVED_SHA256
    )
    assert APPROVED.stat().st_size == bor.BOARD_OF_RECORD_APPROVED_BYTES


def test_the_content_digest_reproduces_the_registered_hash_spec_v1_value():
    """HASH-SPEC-V1 over 'Board I-K'!A3:Q124, reproduced rather than asserted."""
    assert bor.board_content_sha256(APPROVED) == bor.BOARD_OF_RECORD_CONTENT_SHA256


def test_custody_status_reports_verified_and_emits_no_blocker():
    status = bor.board_of_record_status(APPROVED)
    assert status["custody"] == bor.CUSTODY_VERIFIED
    assert status["verified"] is True
    assert status["blocker"] is None
    assert status["historical_board_substitutable"] is False
    assert bor.board_of_record_blockers(APPROVED) == []


def test_the_board_exposes_121_rows_ranked_one_through_121(board):
    assert board.row_count == bor.BOARD_EXPECTED_ROWS == 121
    assert [r.rank for r in board.rows] == list(range(1, 122))
    assert len(set(board.order_by_master_team_id())) == 121
    assert board.sha256 == bor.BOARD_OF_RECORD_APPROVED_SHA256
    assert board.content_sha256 == bor.BOARD_OF_RECORD_CONTENT_SHA256


def test_the_board_binds_to_the_governed_universe(board, canonical_index):
    """121 FBS_MEMBER, 13 SCHEDULE_ONLY_FCS, 134 schedule identities — unchanged."""
    assert len(canonical_index) == 134
    fbs = {s for s, r in canonical_index.items() if r["entity_scope"] == "FBS_MEMBER"}
    fcs = {
        s for s, r in canonical_index.items()
        if r["entity_scope"] == "SCHEDULE_ONLY_FCS"
    }
    assert len(fbs) == 121 and len(fcs) == 13

    bor.validate_against_canonical_universe(board, canonical_index)
    schedule_ids = board.order_by_schedule_id(canonical_index)
    assert len(schedule_ids) == 121
    assert set(schedule_ids) == fbs
    # No schedule-only FCS entity is ranked, and none can be: FCS entities carry
    # no master_team_id in the canonical index at all.
    assert not (set(schedule_ids) & fcs)
    assert all(
        canonical_index[s]["master_team_id"] is None for s in fcs
    )


def test_the_ordering_is_rank_order_and_maps_through_governed_identifiers(
    board, canonical_index
):
    """Ordering comes from Master Team ID, never from team names."""
    assert board.order_by_schedule_id(canonical_index)[0] == (
        canonical_index[
            next(
                s for s, r in canonical_index.items()
                if r["master_team_id"] == board.rows[0].master_team_id
            )
        ]["schedule_id"]
    )


# =============================================================================
# B — filename is not authority, in both directions
# =============================================================================


@pytest.mark.parametrize(
    "variant",
    [
        "2026_Board_I-K_CANONICAL_APPROVED_R1_REISSUE(3).xlsx",
        "2026_Board_I-K_CANONICAL_APPROVED_R1_REISSUE(3)(1).xlsx",
        "2026_Board_I-K_CANONICAL_APPROVED_R1_REISSUE(3)(1) (1).xlsx",
        "2026_Board_I-K_CANONICAL_APPROVED_R1_REISSUE (1).xlsx",
    ],
)
def test_the_approved_bytes_verify_under_download_name_variants(variant, tmp_path):
    """The ruling names one artifact; delivery channels rename it freely."""
    copy = tmp_path / variant
    shutil.copy(APPROVED, copy)
    assert bor.board_of_record_status(copy)["custody"] == bor.CUSTODY_VERIFIED
    assert bor.require_board_of_record(copy).row_count == 121
    assert bor.board_of_record_blockers(copy) == []


def test_the_approved_bytes_verify_even_under_a_foreign_name(tmp_path):
    """Content identity is authoritative, so a misleading name cannot veto it.

    The converse — a correct name over wrong bytes — is refused immediately
    below, which is where the asymmetry actually protects the board.
    """
    copy = tmp_path / "Board_I-H_historical_evidence.xlsx"
    shutil.copy(APPROVED, copy)
    assert bor.board_of_record_status(copy)["custody"] == bor.CUSTODY_VERIFIED


def test_the_canonical_filename_over_wrong_bytes_is_refused(tmp_path):
    """Correct name / wrong digest — the filename-only match, refused."""
    impostor = _synthetic_board(
        tmp_path / bor.BOARD_OF_RECORD_FILENAME, _plausible_rows()
    )
    assert impostor.name == bor.BOARD_OF_RECORD_FILENAME
    status = bor.board_of_record_status(impostor)
    assert status["custody"] == bor.CUSTODY_BINARY_MISMATCH
    assert status["verified"] is False
    assert status["blocker"] == bor.BOARD_OF_RECORD_BLOCKER
    with pytest.raises(GovernanceBlock, match="filename is not authority"):
        bor.require_board_of_record(impostor)


# =============================================================================
# C — every substitution is refused, and named where possible
# =============================================================================


def test_board_i_h_may_not_stand_in(tmp_path):
    ih = _synthetic_board(
        tmp_path / "Model_Parameters_Board_IH.xlsx",
        _plausible_rows(25),
        sheet=bor.HISTORICAL_BOARD_SHEET,
    )
    assert bor.board_of_record_status(ih)["custody"] == bor.CUSTODY_BINARY_MISMATCH
    with pytest.raises(GovernanceBlock):
        bor.require_board_of_record(ih)
    # And the label-level refusal is explicit about why.
    with pytest.raises(GovernanceBlock, match="historical evidence only"):
        bor.reject_historical_board_substitution(bor.HISTORICAL_BOARD_LABEL)


def test_a_pytest_fixture_stand_in_is_refused(tmp_path):
    """A text file wearing the artifact's name — what the harness used to mount."""
    fixture = tmp_path / bor.BOARD_OF_RECORD_FILENAME
    fixture.write_text(
        "harness stand-in for the Board of Record artifact", encoding="utf-8"
    )
    status = bor.board_of_record_status(fixture)
    assert status["custody"] == bor.CUSTODY_BINARY_MISMATCH
    assert status["identified_as"].startswith("UNKNOWN_ARTIFACT")
    assert bor.board_of_record_blockers(fixture) == [bor.BOARD_OF_RECORD_BLOCKER]
    with pytest.raises(GovernanceBlock):
        bor.require_board_of_record(fixture)


def test_a_synthetic_workbook_with_the_right_shape_is_refused(tmp_path):
    """Correct sheet, correct 17 columns, correct 121 rows — and still not the Board."""
    synthetic = _synthetic_board(tmp_path / "synthetic.xlsx", _plausible_rows())
    grid = bor._read_board_grid(synthetic)
    # It really does satisfy schema and internal identity...
    rows = bor._validate_identity(bor._validate_schema(grid, synthetic), synthetic)
    assert len(rows) == 121
    # ...and is refused anyway, because content identity is what governs.
    assert bor.board_of_record_status(synthetic)["custody"] == (
        bor.CUSTODY_BINARY_MISMATCH
    )
    with pytest.raises(GovernanceBlock):
        bor.require_board_of_record(synthetic)


def test_a_truncated_workbook_is_refused(tmp_path):
    truncated = tmp_path / bor.BOARD_OF_RECORD_FILENAME
    truncated.write_bytes(APPROVED.read_bytes()[: bor.BOARD_OF_RECORD_APPROVED_BYTES // 2])
    assert not zipfile.is_zipfile(truncated)
    assert bor.board_of_record_status(truncated)["custody"] == (
        bor.CUSTODY_BINARY_MISMATCH
    )
    with pytest.raises(GovernanceBlock):
        bor.require_board_of_record(truncated)
    # Read directly, it is classified as an unreadable container, not as rows.
    with pytest.raises(InputValidationError, match=bor.CUSTODY_NOT_A_WORKBOOK):
        bor.board_content_sha256(truncated)


def test_a_corrupted_workbook_is_refused(tmp_path):
    corrupted = tmp_path / bor.BOARD_OF_RECORD_FILENAME
    data = bytearray(APPROVED.read_bytes())
    for i in range(200, 4000, 7):
        data[i] ^= 0xFF
    corrupted.write_bytes(bytes(data))
    assert bor.board_of_record_status(corrupted)["custody"] == (
        bor.CUSTODY_BINARY_MISMATCH
    )
    with pytest.raises(GovernanceBlock):
        bor.require_board_of_record(corrupted)


def test_a_resaved_approved_workbook_is_refused_although_content_survives(tmp_path):
    """The two digests are not interchangeable, and the binary one is not waived.

    A re-save preserves the governed table and loses the container bytes. For
    the schedule, a ruling accepts that trade. For the Board of Record no ruling
    does, so the artifact is refused even though its rows are provably intact.
    """
    resaved = tmp_path / bor.BOARD_OF_RECORD_FILENAME
    shutil.copy(APPROVED, resaved)
    wb = load_workbook(resaved)
    wb.save(resaved)

    assert bor.board_content_sha256(resaved) == bor.BOARD_OF_RECORD_CONTENT_SHA256
    assert hashlib.sha256(resaved.read_bytes()).hexdigest() != (
        bor.BOARD_OF_RECORD_APPROVED_SHA256
    )
    assert bor.board_of_record_status(resaved)["custody"] == bor.CUSTODY_BINARY_MISMATCH
    with pytest.raises(GovernanceBlock):
        bor.require_board_of_record(resaved)


def test_an_edited_approved_workbook_loses_the_content_digest(tmp_path):
    """An edit is distinguishable from a re-save, which is why both are tracked."""
    edited = tmp_path / bor.BOARD_OF_RECORD_FILENAME
    shutil.copy(APPROVED, edited)
    wb = load_workbook(edited)
    wb[bor.BOARD_SHEET]["B4"] = "NOT THE APPROVED TEAM"
    wb.save(edited)
    assert bor.board_content_sha256(edited) != bor.BOARD_OF_RECORD_CONTENT_SHA256


@pytest.mark.parametrize("digest", sorted(bor.KNOWN_NON_APPROVED_SHA256))
def test_known_non_approved_artifacts_are_named_not_merely_refused(digest):
    """"You mounted the superseded predecessor" is actionable; "mismatch" is not."""
    assert digest != bor.BOARD_OF_RECORD_APPROVED_SHA256
    assert bor.KNOWN_NON_APPROVED_SHA256[digest]


def test_the_approved_digest_is_not_in_the_refused_register():
    assert bor.BOARD_OF_RECORD_APPROVED_SHA256 not in bor.KNOWN_NON_APPROVED_SHA256


# =============================================================================
# D — schema validation
# =============================================================================


def test_a_missing_board_sheet_is_refused(tmp_path):
    other = _synthetic_board(
        tmp_path / "no_board_sheet.xlsx", _plausible_rows(), sheet="Something Else"
    )
    with pytest.raises(InputValidationError, match=bor.CUSTODY_SCHEMA_INVALID):
        bor._read_board_grid(other)


def test_a_renamed_column_is_refused(tmp_path):
    grid = _grid(_plausible_rows())
    grid[0][16] = "Team ID"
    with pytest.raises(InputValidationError, match=bor.CUSTODY_SCHEMA_INVALID):
        bor._validate_schema(grid, tmp_path / "x.xlsx")


def test_a_reordered_header_is_refused(tmp_path):
    grid = _grid(_plausible_rows())
    grid[0][4], grid[0][5] = grid[0][5], grid[0][4]
    with pytest.raises(InputValidationError, match=bor.CUSTODY_SCHEMA_INVALID):
        bor._validate_schema(grid, tmp_path / "x.xlsx")


@pytest.mark.parametrize("count", [0, 25, 120, 122, 134])
def test_a_wrong_row_count_is_refused(count, tmp_path):
    with pytest.raises(InputValidationError, match="expected exactly 121"):
        bor._validate_schema(_grid(_plausible_rows(count)), tmp_path / "x.xlsx")


def test_the_declared_columns_match_the_hashed_range():
    """A3:Q124 is 17 columns by 1 header + 121 rows; the constants must agree."""
    assert len(bor.BOARD_COLUMNS) == bor.BOARD_LAST_COL - bor.BOARD_FIRST_COL + 1 == 17
    assert bor.BOARD_LAST_DATA_ROW - bor.BOARD_FIRST_DATA_ROW + 1 == 121
    assert bor.BOARD_CONTENT_RANGE == "A3:Q124"


# =============================================================================
# E — governed identity validation
# =============================================================================


def test_duplicate_team_ids_are_refused(tmp_path):
    rows = _plausible_rows()
    rows[50][16] = rows[10][16]
    with pytest.raises(InputValidationError, match="repeats master team ids"):
        bor._validate_identity(rows, tmp_path / "x.xlsx")


def test_non_contiguous_ranks_are_refused(tmp_path):
    rows = _plausible_rows()
    rows[70][0] = 999
    with pytest.raises(InputValidationError, match="contiguous sequence"):
        bor._validate_identity(rows, tmp_path / "x.xlsx")


def test_a_null_identifier_is_refused(tmp_path):
    rows = _plausible_rows()
    rows[3][16] = None
    with pytest.raises(InputValidationError, match="null Rank, Team or Master Team ID"):
        bor._validate_identity(rows, tmp_path / "x.xlsx")


def _board_from_ids(ids: list[str]) -> bor.BoardOfRecord:
    return bor.BoardOfRecord(
        identity=bor.BOARD_OF_RECORD_FILENAME,
        path=APPROVED,
        sha256=bor.BOARD_OF_RECORD_APPROVED_SHA256,
        content_sha256=bor.BOARD_OF_RECORD_CONTENT_SHA256,
        rows=tuple(
            bor.BoardRow(
                rank=i,
                team_name=f"Team {i}",
                short_name=f"T{i}",
                conference="Test",
                master_team_id=mid,
                committee=0.5,
                power=0.5,
            )
            for i, mid in enumerate(ids, start=1)
        ),
    )


def test_missing_fbs_ids_are_refused(board, canonical_index):
    short = _board_from_ids(list(board.order_by_master_team_id())[:-1])
    with pytest.raises(InputValidationError, match="omits governed FBS master team ids"):
        bor.validate_against_canonical_universe(short, canonical_index)


def test_an_unexpected_fcs_entity_is_refused(board, canonical_index):
    ids = list(board.order_by_master_team_id())
    ids[0] = "FCS-SCHEDULE-ONLY-OPPONENT"
    with pytest.raises(InputValidationError, match="not governed FBS members"):
        bor.validate_against_canonical_universe(_board_from_ids(ids), canonical_index)


def test_an_unknown_master_id_cannot_be_mapped_to_a_schedule_id(board, canonical_index):
    ids = list(board.order_by_master_team_id())
    ids[5] = "NOT-A-GOVERNED-ID"
    with pytest.raises(InputValidationError, match="no FBS_MEMBER in the canonical"):
        _board_from_ids(ids).order_by_schedule_id(canonical_index)


def test_require_board_of_record_enforces_the_universe_when_given_the_index(
    canonical_index,
):
    """Passing the index turns the universe check on; it is not optional then."""
    board = bor.require_board_of_record(APPROVED, canonical_index)
    assert board.row_count == 121


# =============================================================================
# F — fail-closed and blocker emission
# =============================================================================


def test_an_unconfigured_board_fails_closed_and_blocks():
    status = bor.board_of_record_status(None)
    assert status["mounted"] is False
    assert status["custody"] == bor.CUSTODY_NOT_CONFIGURED
    assert status["blocker"] == bor.BOARD_OF_RECORD_BLOCKER
    assert bor.board_of_record_blockers(None) == [bor.BOARD_OF_RECORD_BLOCKER]
    with pytest.raises(GovernanceBlock):
        bor.require_board_of_record(None)


def test_an_absent_path_fails_closed_and_blocks(tmp_path):
    missing = tmp_path / bor.BOARD_OF_RECORD_FILENAME
    status = bor.board_of_record_status(missing)
    assert status["custody"] == bor.CUSTODY_NOT_MOUNTED
    assert status["blocker"] == bor.BOARD_OF_RECORD_BLOCKER
    with pytest.raises(GovernanceBlock, match="not mounted"):
        bor.require_board_of_record(missing)


def _write_fixture_text(path: Path) -> Path:
    path.write_text("harness stand-in", encoding="utf-8")
    return path


def _write_truncated(path: Path) -> Path:
    path.write_bytes(APPROVED.read_bytes()[:1000])
    return path


@pytest.mark.parametrize(
    "make",
    [
        pytest.param(lambda p: _synthetic_board(p, _plausible_rows()), id="synthetic"),
        pytest.param(_write_fixture_text, id="fixture"),
        pytest.param(_write_truncated, id="truncated"),
    ],
)
def test_the_config_gate_blocks_on_any_unverified_mount(make, tmp_path):
    """A merely *present* file never clears the gate — the whole point of the change."""
    artifact = make(tmp_path / bor.BOARD_OF_RECORD_FILENAME)
    assert artifact.exists()
    assert bor.board_of_record_blockers(artifact) == [bor.BOARD_OF_RECORD_BLOCKER]


def test_no_board_rows_are_exposed_by_any_failing_path(tmp_path):
    """Failure never yields a partial board — it raises before rows exist."""
    bad = _synthetic_board(tmp_path / bor.BOARD_OF_RECORD_FILENAME, _plausible_rows())
    for candidate in (None, tmp_path / "absent.xlsx", bad):
        with pytest.raises(GovernanceBlock):
            bor.require_board_of_record(candidate)


def test_the_live_config_mounts_the_approved_board_and_clears_only_that_gate():
    cfg = V3Config.from_json(CONFIG)
    assert cfg.inputs.board_of_record_xlsx == APPROVED
    blockers = cfg.execution_blockers()
    assert bor.BOARD_OF_RECORD_BLOCKER not in blockers
    # Calibration is a different lane and is untouched by this mount.
    assert [b for b in blockers if b.startswith("calibration.")]


def test_the_board_is_not_designated_as_the_committee_tb4_fallback():
    """Custody settled; the TB4 first-November fallback authority still is not.

    Mounting the Board of Record must not be read as answering a question no
    ruling has answered.
    """
    from ncaaf_engine.simulation.dynamic_weekly_mc_v3 import committee_policy

    assert committee_policy.FIRST_BOARD_TB4_BLOCKER
    with pytest.raises(GovernanceBlock, match="COMMITTEE_TB4"):
        committee_policy.break_committee_tie(
            "A",
            "B",
            committee_policy.CommitteeTiebreakInputs(
                head_to_head=lambda a, b: None,
                common_opponent_score=lambda a, b: (None, None),
                strength_of_schedule=lambda t: None,
                previous_board=None,
            ),
            is_first_november_board=True,
        )


def test_the_custody_record_matches_the_live_state():
    """The lane's own evidence record cannot drift from what the code reports."""
    import json

    record = json.loads(
        (ROOT / "reference/dynamic_weekly_mc_v3/V3_BOARD_IK_CUSTODY.json").read_text(
            encoding="utf-8"
        )
    )
    assert record["binary_identity"]["computed_sha256"] == (
        bor.BOARD_OF_RECORD_APPROVED_SHA256
    )
    assert record["binary_identity"]["verified"] is True
    assert record["content_identity"]["computed_sha256"] == (
        bor.BOARD_OF_RECORD_CONTENT_SHA256
    )
    assert record["content_identity"]["verified"] is True
    assert record["custody_status"] == bor.CUSTODY_VERIFIED
    assert record["identity_status"]["governed_universe_preserved"] == {
        "schedule_identities": 134,
        "fbs_member": 121,
        "schedule_only_fcs": 13,
    }
    # Exactly one blocker retired, and it is the one this lane owns.
    assert record["blockers"]["retired"] == [bor.BOARD_OF_RECORD_BLOCKER]
    assert record["blockers"]["other_blockers_retired"] == []
    assert record["blockers"]["retirement_is_not_a_ruling"] is True

    cfg = V3Config.from_json(CONFIG)
    from ncaaf_engine.simulation.dynamic_weekly_mc_v3.engine import DynamicWeeklyMCV3

    live = sorted(DynamicWeeklyMCV3(cfg).preflight()["execution_blockers"])
    assert record["blockers"]["after"] == live
    assert record["blockers"]["after_count"] == len(live) == 8


def test_the_r2_r3_r4_status_records_were_not_rewritten():
    """Historical governance records keep their pre-mount state, by design."""
    import json

    ref = ROOT / "reference/dynamic_weekly_mc_v3"
    for name in ("V3_GOVERNANCE_STATUS_R3.json", "V3_GOVERNANCE_STATUS_R4.json"):
        status = json.loads((ref / name).read_text(encoding="utf-8"))
        assert bor.BOARD_OF_RECORD_BLOCKER in status["live_blockers"]
        assert status["live_blocker_count"] == 9
    r3 = json.loads((ref / "V3_GOVERNANCE_STATUS_R3.json").read_text(encoding="utf-8"))
    assert r3["board_of_record"]["mounted"] is False
    assert r3["board_of_record"]["required_sha256"] == (
        bor.BOARD_OF_RECORD_APPROVED_SHA256
    )
